#!/bin/sh

# pull rebase 检查
IS_REBASE=$(git config pull.rebase)

if [[ $IS_REBASE != false ]]; then
  git config --replace-all pull.rebase false
  printf '\n\033[32m Massage:自动设置git config pull.rebase => false \033[0m\n\n'
fi

# fast forwatd 检查
FAST_FORWARD=$(git config merge.ff)

if [[ $FAST_FORWARD != true ]]; then
  git config --replace-all merge.ff true
  printf '\n\033[32m Massage:自动设置git config merge.ff => true \033[0m\n\n'
fi

changedfiles=( `git diff --name-only --no-commit-id HEAD@{1} HEAD` )

#bower auto update
if [[ "${changedfiles[*]}" =~ "wap/bower.json" ]]; then
    echo "wap/bower.json has changed bower installing...."
    cd wap && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "sass/bower.json" ]]; then
    echo "sass/bower.json has changed bower installing...."
    cd sass && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "www/bower.json" ]]; then
    echo "www/bower.json has changed bower installing...."
    cd www && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "fenxiao/bower.json" ]]; then
    echo "fenxiao/bower.json has changed bower installing...."
    cd fenxiao && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "intro/bower.json" ]]; then
    echo "intro/bower.json has changed bower installing...."
    cd intro && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "pf/bower.json" ]]; then
    echo "pf/bower.json has changed bower installing...."
    cd pf && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "pinjian/bower.json" ]]; then
    echo "pinjian/bower.json has changed bower installing...."
    cd pinjian && bower install && bower update && cd ..
fi

if [[ "${changedfiles[*]}" =~ "fuwu/bower.json" ]]; then
    echo "fuwu/bower.json has changed bower installing...."
    cd fuwu && bower install && bower update && cd ..
fi

#iron-front auto update
if [[ "${changedfiles[*]}" =~ "fenxiao/package.json" ]]; then
    echo "iron-front/package.json has changed, npm installing...."
    cd fenxiao && npm install --registry=http://registry.npm.taobao.org && cd ..
fi

#update hooks auto update
if [[ "${changedfiles[*]}" =~ ".git_hooks/update_git_hooks.sh" ]]; then
    echo "update git hooks"
    felint update
    exit 0
fi

if [[ "${changedfiles[*]}" =~ ".git_hooks/.eslintrc_es5" ]]; then
    echo "update git eslintrc_es5"
    felint update
    exit 0
fi

if [[ "${changedfiles[*]}" =~ ".git_hooks/.eslintrc_es6" ]]; then
    echo "update git eslintrc_es6"
    felint update
    exit 0
fi

if [[ "${changedfiles[*]}" =~ ".git_hooks/.eslintignore" ]]; then
    echo "update git eslintignore"
    felint update
    exit 0
fi